-- DEPRECATED: The app uses in-memory cart (backend/src/store/cartStore.js), not database.
-- Do not run this file unless you revert to DB-backed panier and restore Panier/PanierProduit models.
-- Kept only for reference. To drop panier tables instead, run: drop_panier_tables.sql
